apiVersion: v1
kind: Namespace
metadata:
  name: ip-exhaustion-demo
  labels:
    name: ip-exhaustion-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: ip-exhaustion-demo
  labels:
    app: podinfo
spec:
  replicas: 100
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      nodeSelector:
        eks.amazonaws.com/nodeclass: large-ip-pool-nodeclass
      containers:
      - name: podinfo
        image: stefanprodan/podinfo:6.5.3
        ports:
        - containerPort: 9898
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        - name: PODINFO_UI_MESSAGE
          value: "IPv4 Exhaustion Demo"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: ip-exhaustion-demo
  labels:
    app: podinfo
spec:
  selector:
    app: podinfo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
  type: ClusterIP 