apiVersion: apps/v1
kind: Deployment
metadata:
  name: general-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: general-demo
  template:
    metadata:
      labels:
        app: general-demo
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.5.3
          ports:
            - containerPort: 9898 